### ISSUE TITLE
ClassCastException with Slick

### ISSUE THREAD

**Issue by osbornk** [opentracing-contrib/java-concurrent#19]
I am using OpenTracing Special Agent with Play and Slick. If I include the "concurrent" rule, I get the following error with Slick.

```
[error] ErrorHandler - class io.opentracing.contrib.specialagent.rule.concurrent.TracedRunnable cannot be cast to class slick.util.AsyncExecutor$PrioritizedRunnable (io.opentracing.contrib.specialagent.rule.concurrent.TracedRunnable is in unnamed module of loader 'bootstrap'; slick.util.AsyncExecutor$PrioritizedRunnable is in unnamed module of loader play.runsupport.NamedURLClassLoader @70355caa)
java.lang.ClassCastException: class io.opentracing.contrib.specialagent.rule.concurrent.TracedRunnable cannot be cast to class slick.util.AsyncExecutor$PrioritizedRunnable (io.opentracing.contrib.specialagent.rule.concurrent.TracedRunnable is in unnamed module of loader 'bootstrap'; slick.util.AsyncExecutor$PrioritizedRunnable is in unnamed module of loader play.runsupport.NamedURLClassLoader @70355caa)
	at slick.util.ManagedArrayBlockingQueue.offer(ManagedArrayBlockingQueue.scala:17)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1347)
	at slick.util.AsyncExecutor$$anon$1$$anon$4.execute(AsyncExecutor.scala:163)
	at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction(BasicBackend.scala:265)
	at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction$(BasicBackend.scala:263)
```

Looks like it is trying to instrument something it shouldn't. If this issue should be part of the Special Agent instead, please let me know.

If I don't include the concurrent plugin, there are no errors. But then the tracer is not propagated properly.

**Comment by pavolloffay** [comment]
It seems like special agent issue. Could you please report it there?
